name: koel_audio_transcription_test
description: Dart integration test for Koel Labs audio transcription API

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  web_socket_channel: ^2.4.0
  test: ^1.24.0
  typed_data: ^1.3.2
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
